name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1

    - name: Build firmware
      run: |
        . $IDF_PATH/export.sh
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: build/firmware.bin
