name: Build and Release ESP32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s3

    - name: Build firmware
      run: |
        . $IDF_PATH/export.sh
        idf.py build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/firmware.bin
        tag_name: v${{ github.sha }}
